#!/usr/bin/env python3
"""Generate the golden, foggy, cyclic 3D-noise card overlay used by The Second Lesson's
Order affliction.

Writes two files:
  - shaders/order_overlay.gdshader   (a canvas_item shader; the octave count is baked in as a
                                       literal loop bound at generation time, not a runtime
                                       uniform, since GLSL loop bounds must be compile-time
                                       constants on some renderers)
  - scenes/cards/overlays/afflictions/<entry>.tscn (a Control root with a ColorRect using the
                                       shader, matching AfflictionModel.CreateOverlay()'s
                                       Instantiate<Control>() expectation)

AfflictionModel.OverlayPath is NOT virtual and is always computed as
"res://scenes/cards/overlays/afflictions/" + Id.Entry.ToLowerInvariant() + ".tscn". Id.Entry comes
from ModelDb.GetEntry(type) = StringHelper.Slugify(type.Name) with no mod-namespace prefix (traced
through AbstractModel's constructor and ModelDb.GetId — no BaseLib patch touches this), so for the
Order affliction class Id.Entry resolves to "order", which is the default --entry value here.

Re-run with different flags any time to tune the look; both output files are fully regenerated.
"""

import argparse
from pathlib import Path

ROOT = Path(__file__).parent

SHADER_TEMPLATE = """shader_type canvas_item;

// Golden, foggy, cyclic 3D-noise card overlay (generated by generate_order_overlay.py).
uniform vec3 gold_color : source_color = vec3({r:.3f}, {g:.3f}, {b:.3f});
uniform float base_opacity : hint_range(0.0, 1.0) = {opacity:.3f};
uniform float noise_scale = {noise_scale:.3f};
uniform float speed = {speed:.3f};

float order_overlay_hash(vec3 p) {{
    p = fract(p * 0.3183099 + vec3(0.1, 0.2, 0.3));
    p *= 17.0;
    return fract(p.x * p.y * p.z * (p.x + p.y + p.z));
}}

float order_overlay_noise(vec3 p) {{
    vec3 i = floor(p);
    vec3 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    float n000 = order_overlay_hash(i + vec3(0.0, 0.0, 0.0));
    float n100 = order_overlay_hash(i + vec3(1.0, 0.0, 0.0));
    float n010 = order_overlay_hash(i + vec3(0.0, 1.0, 0.0));
    float n110 = order_overlay_hash(i + vec3(1.0, 1.0, 0.0));
    float n001 = order_overlay_hash(i + vec3(0.0, 0.0, 1.0));
    float n101 = order_overlay_hash(i + vec3(1.0, 0.0, 1.0));
    float n011 = order_overlay_hash(i + vec3(0.0, 1.0, 1.0));
    float n111 = order_overlay_hash(i + vec3(1.0, 1.0, 1.0));
    float nx00 = mix(n000, n100, f.x);
    float nx10 = mix(n010, n110, f.x);
    float nx01 = mix(n001, n101, f.x);
    float nx11 = mix(n011, n111, f.x);
    float nxy0 = mix(nx00, nx10, f.y);
    float nxy1 = mix(nx01, nx11, f.y);
    return mix(nxy0, nxy1, f.z);
}}

// Octave count ({octaves}) is baked in as a literal loop bound at generation time.
float order_overlay_fbm(vec3 p) {{
    float value = 0.0;
    float amplitude = 0.5;
    for (int i = 0; i < {octaves}; i++) {{
        value += amplitude * order_overlay_noise(p);
        p *= 2.0;
        amplitude *= 0.5;
    }}
    return value;
}}

void fragment() {{
    // Slicing through the 3rd noise axis over TIME is what makes this animate smoothly and
    // continuously forever, with no baked frames and no hard loop point.
    vec3 p = vec3(UV * noise_scale, TIME * speed);
    float n = order_overlay_fbm(p);
    COLOR = vec4(gold_color, n * base_opacity);
}}
"""

SCENE_TEMPLATE = """[gd_scene load_steps=3 format=3]

[ext_resource type="Shader" path="res://shaders/order_overlay.gdshader" id="1"]

[sub_resource type="ShaderMaterial" id="1"]
shader = ExtResource("1")

[node name="OrderOverlay" type="Control"]
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
grow_horizontal = 2
grow_vertical = 2
mouse_filter = 2

[node name="ColorRect" type="ColorRect" parent="."]
material = SubResource("1")
anchors_preset = 15
anchor_right = 1.0
anchor_bottom = 1.0
grow_horizontal = 2
grow_vertical = 2
mouse_filter = 2
color = Color(1, 1, 1, 1)
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--color", default="1.0,0.85,0.35", help="gold_color as r,g,b in 0-1 range")
    parser.add_argument("--opacity", type=float, default=0.18, help="peak overlay opacity (0-1)")
    parser.add_argument("--noise-scale", type=float, default=6.0, help="spatial noise frequency")
    parser.add_argument("--speed", type=float, default=0.15, help="animation speed through the 3rd noise axis")
    parser.add_argument("--octaves", type=int, default=3, help="fbm octave count, baked in at generation time")
    parser.add_argument(
        "--entry", default="order",
        help="lowercased Id.Entry the scene must be named after (see module docstring)")
    args = parser.parse_args()

    r, g, b = (float(x) for x in args.color.split(","))

    shader_path = ROOT / "shaders" / "order_overlay.gdshader"
    shader_path.parent.mkdir(parents=True, exist_ok=True)
    shader_path.write_text(SHADER_TEMPLATE.format(
        r=r, g=g, b=b, opacity=args.opacity, noise_scale=args.noise_scale,
        speed=args.speed, octaves=args.octaves))
    print(f"Wrote {shader_path.relative_to(ROOT)}")

    scene_path = ROOT / "scenes" / "cards" / "overlays" / "afflictions" / f"{args.entry}.tscn"
    scene_path.parent.mkdir(parents=True, exist_ok=True)
    scene_path.write_text(SCENE_TEMPLATE)
    print(f"Wrote {scene_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
