#!/usr/bin/env python3
"""Generate the pulsing red heartbeat boundary-glow shader used by The Second Lesson's Order
affliction.

Writes shaders/order_overlay.gdshader (a canvas_item shader; the octave count is baked in as a
literal loop bound at generation time, not a runtime uniform, since GLSL loop bounds must be
compile-time constants on some renderers).

The effect layers three things multiplicatively:
  - a border mask (order_overlay_edge_dist): 1.0 at the card's edge, fading to 0.0 over
    --border-width of UV space toward the interior, so the glow rings the boundary and fades
    inward instead of washing the whole card.
  - a heartbeat envelope (order_overlay_heartbeat): two beats ("lub-dub") per --pulse-period, each
    with an asymmetric attack/decay shape (order_overlay_pulse_shape) — a very quick rise
    (--attack) followed by a slightly slower fall (--decay), like an actual heartbeat rather than a
    symmetric sine pulse. The envelope is never fully zero: it's used to blend between
    --opacity-low (the always-visible resting glow) and --opacity-high (the peak during a beat),
    so the effect stays visible at all times and only brightens/dims with each pulse.
  - the original foggy 3D-noise fbm, still scrolling through TIME on its own axis, multiplied
    directly (not blended against a floor) into the final alpha, so the moving noise pattern
    visibly gates/reveals the boundary glow instead of just gently brightening/dimming it.

The overlay is attached directly in code (TheUnderstudyCode/Patches/OrderOverlayPatch.cs), not via
a .tscn scene + AfflictionModel.OverlayPath/CreateOverlay(). That convention is fixed/non-virtual
and routes through PreloadManager.Cache.GetScene, which never learned about the scene without extra
per-character preload wiring, and even after that wiring the scene-instantiated overlay still never
rendered visibly in-game for unknown reasons. OrderOverlayPatch instead loads this shader directly
with GD.Load and assigns it to a plain ColorRect's Material — the "apply a shader to a node without
children" pattern from https://github.com/Alchyr/ModTemplate-StS2/wiki/Shaders. There used to be a
generated scenes/cards/overlays/afflictions/order.tscn here too; it's deleted now so
AfflictionModel.HasOverlay is false for Order and NCard's own built-in-overlay branch doesn't also
try (and fail) to attach a competing copy.

Re-run with different flags any time to tune the look; the shader file is fully regenerated.
"""

import argparse
from pathlib import Path

ROOT = Path(__file__).parent

SHADER_TEMPLATE = """shader_type canvas_item;

// Pulsing red heartbeat boundary-glow, foggy moving noise (generated by generate_order_overlay.py).
uniform vec3 gold_color : source_color = vec3({r:.3f}, {g:.3f}, {b:.3f});
uniform float opacity_low : hint_range(0.0, 1.0) = {opacity_low:.3f};
uniform float opacity_high : hint_range(0.0, 1.0) = {opacity_high:.3f};
uniform float noise_scale = {noise_scale:.3f};
uniform float speed = {speed:.3f};
uniform float border_width : hint_range(0.0, 0.5) = {border_width:.3f};
uniform float pulse_period : hint_range(0.1, 5.0) = {pulse_period:.3f};
uniform float attack_width : hint_range(0.001, 0.5) = {attack_width:.4f};
uniform float decay_width : hint_range(0.001, 0.5) = {decay_width:.4f};

float order_overlay_hash(vec3 p) {{
    p = fract(p * 0.3183099 + vec3(0.1, 0.2, 0.3));
    p *= 17.0;
    return fract(p.x * p.y * p.z * (p.x + p.y + p.z));
}}

float order_overlay_noise(vec3 p) {{
    vec3 i = floor(p);
    vec3 f = fract(p);
    f = f * f * (3.0 - 2.0 * f);
    float n000 = order_overlay_hash(i + vec3(0.0, 0.0, 0.0));
    float n100 = order_overlay_hash(i + vec3(1.0, 0.0, 0.0));
    float n010 = order_overlay_hash(i + vec3(0.0, 1.0, 0.0));
    float n110 = order_overlay_hash(i + vec3(1.0, 1.0, 0.0));
    float n001 = order_overlay_hash(i + vec3(0.0, 0.0, 1.0));
    float n101 = order_overlay_hash(i + vec3(1.0, 0.0, 1.0));
    float n011 = order_overlay_hash(i + vec3(0.0, 1.0, 1.0));
    float n111 = order_overlay_hash(i + vec3(1.0, 1.0, 1.0));
    float nx00 = mix(n000, n100, f.x);
    float nx10 = mix(n010, n110, f.x);
    float nx01 = mix(n001, n101, f.x);
    float nx11 = mix(n011, n111, f.x);
    float nxy0 = mix(nx00, nx10, f.y);
    float nxy1 = mix(nx01, nx11, f.y);
    return mix(nxy0, nxy1, f.z);
}}

// Octave count ({octaves}) is baked in as a literal loop bound at generation time. Normalized by
// total amplitude so the result properly spans [0,1] regardless of octave count — needed now that
// it's multiplied directly into alpha rather than blended against a floor.
float order_overlay_fbm(vec3 p) {{
    float value = 0.0;
    float amplitude = 0.5;
    float total_amplitude = 0.0;
    for (int i = 0; i < {octaves}; i++) {{
        value += amplitude * order_overlay_noise(p);
        total_amplitude += amplitude;
        p *= 2.0;
        amplitude *= 0.5;
    }}
    return value / total_amplitude;
}}

// Distance (in UV space) from the nearest edge of the rect: 0.0 exactly on the border, growing
// toward the interior.
float order_overlay_edge_dist(vec2 uv) {{
    return min(min(uv.x, 1.0 - uv.x), min(uv.y, 1.0 - uv.y));
}}

// Asymmetric Gaussian: a very quick rise before `center` (using `attack`) and a slightly slower
// fall after it (using `decay`) — this is what gives each beat its "thump" rather than a smooth,
// symmetric pulse.
float order_overlay_pulse_shape(float phase, float center, float attack, float decay) {{
    float d = phase - center;
    float w = d < 0.0 ? attack : decay;
    return exp(-pow(d / w, 2.0));
}}

// Two beats ("lub-dub") per period, each with the fast-attack/slow-decay shape above. Returns an
// envelope in [0,1]; 0 between beats (rest), 1 at the sharpest point of a beat. Never subtracted
// to silence — the caller blends this against a resting opacity floor, so the effect stays visible
// throughout and only brightens on a beat.
float order_overlay_heartbeat(float t, float period, float attack, float decay) {{
    float phase = fract(t / period);
    float lub = order_overlay_pulse_shape(phase, 0.05, attack, decay);
    float dub = order_overlay_pulse_shape(phase, 0.22, attack, decay) * 0.7;
    return clamp(lub + dub, 0.0, 1.0);
}}

void fragment() {{
    // Slicing through the 3rd noise axis over TIME is what makes this animate smoothly and
    // continuously forever, with no baked frames and no hard loop point.
    vec3 p = vec3(UV * noise_scale, TIME * speed);
    float n = order_overlay_fbm(p);

    float edge_dist = order_overlay_edge_dist(UV);
    float border_mask = 1.0 - smoothstep(0.0, border_width, edge_dist);

    float envelope = order_overlay_heartbeat(TIME, pulse_period, attack_width, decay_width);
    float pulse_opacity = mix(opacity_low, opacity_high, envelope);

    float alpha = pulse_opacity * border_mask * n;
    // Multiply by the incoming COLOR.a (which already carries the node's modulate/self_modulate),
    // rather than overwriting COLOR outright — a full overwrite would silently discard any fade
    // driven by animating the ColorRect's Modulate from C#, since that tween has nothing left to
    // multiply against.
    COLOR = vec4(gold_color, alpha * COLOR.a);
}}
"""


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--color", default="0.85,0.12,0.12", help="overlay color as r,g,b in 0-1 range")
    parser.add_argument("--opacity-low", type=float, default=0.35, help="resting opacity (0-1) at the border between beats")
    parser.add_argument("--opacity-high", type=float, default=0.70, help="peak opacity (0-1) at the border during a beat")
    parser.add_argument("--noise-scale", type=float, default=6.0, help="spatial noise frequency")
    parser.add_argument("--speed", type=float, default=0.15, help="animation speed through the 3rd noise axis")
    parser.add_argument("--octaves", type=int, default=3, help="fbm octave count, baked in at generation time")
    parser.add_argument("--border-width", type=float, default=0.35, help="how far inward (in UV fraction) the boundary glow fades, 0-0.5")
    parser.add_argument("--pulse-period", type=float, default=1.1, help="seconds per heartbeat cycle")
    parser.add_argument("--attack", type=float, default=0.015, help="phase width of each beat's rise; smaller = snappier/quicker attack")
    parser.add_argument("--decay", type=float, default=0.06, help="phase width of each beat's fall; larger = slower decay")
    args = parser.parse_args()

    r, g, b = (float(x) for x in args.color.split(","))

    shader_path = ROOT / "shaders" / "order_overlay.gdshader"
    shader_path.parent.mkdir(parents=True, exist_ok=True)
    shader_path.write_text(SHADER_TEMPLATE.format(
        r=r, g=g, b=b, opacity_low=args.opacity_low, opacity_high=args.opacity_high,
        noise_scale=args.noise_scale, speed=args.speed, octaves=args.octaves,
        border_width=args.border_width, pulse_period=args.pulse_period,
        attack_width=args.attack, decay_width=args.decay))
    print(f"Wrote {shader_path.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
