#!/usr/bin/env python3
"""Regenerate the mechanical per-asset art briefs from the shipping localization files.

art/assets/CARDS.md, POWERS.md and RELICS_POTIONS.md are one row per file an artist has to draw, and
every row's name, description and filename comes straight from TheUnderstudy/localization/eng/*.json.
Generating them means the brief cannot drift from the game: rename a card and the row, the slug and the
required filename all move together.

The other docs in art/ are written by hand — they describe intent, not inventory.

Usage:  python3 scripts/gen-art-docs.py
"""
import json
import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parent.parent
LOC = ROOT / "TheUnderstudy" / "localization" / "eng"
IMAGES = ROOT / "TheUnderstudy" / "images"
OUT = ROOT / "art" / "assets"
PREFIX = "THEUNDERSTUDY-"

# Mirrors ArtCoverage.PowersWithoutOwnIcon — powers that never need art of their own.
POWERS_WITHOUT_ICON = {
    "THEUNDERSTUDY-INVERT_TRACKER_POWER",   # always-hidden observer power
    "THEUNDERSTUDY-TUNED_LOCK_POWER",       # always-hidden observer power
    "THEUNDERSTUDY-TUNED_COUNTER_POWER",    # aliased to the Tuned icon by TunedCounterPower
}

BANNER = ("<!-- GENERATED by scripts/gen-art-docs.py from TheUnderstudy/localization/eng/*.json."
          " Do not edit by hand — rerun the script. -->")


def table(name):
    return json.loads((LOC / f"{name}.json").read_text())


def ids(name):
    t = table(name)
    return sorted({k.split(".")[0] for k in t if k.startswith(PREFIX)})


def slug(loc_id):
    return loc_id[len(PREFIX):].lower()


def clean(text):
    """Loc markup -> readable prose for a brief; keep the words, drop the tags."""
    if not text:
        return ""
    text = re.sub(r"\[/?[a-zA-Z]+\]", "", text)   # [gold]...[/gold] -> plain words
    text = re.sub(r"\{[^}]*\}", "X", text)        # {Damage:diff()} / {Amount} -> X (a number at runtime)
    return text.replace("\n", " ").replace("|", r"\|").strip()


def status(rel):
    return "shipped" if (IMAGES / rel).exists() else "**missing**"


def write(name, body):
    (OUT / name).write_text(body)
    print(f"wrote art/assets/{name}")


def cards_doc():
    t = table("cards")
    rows = []
    for i in ids("cards"):
        s = slug(i)
        rel = f"card_portraits/{s}.png"
        rows.append(f"| `{s}.png` | {t.get(i + '.title', '')} | {clean(t.get(i + '.description'))} | {status(rel)} |")
    return f"""# Card portraits

{BANNER}

**{len(rows)} images · 500x380 · `TheUnderstudy/images/card_portraits/<slug>.png`**

One finished image per card serves both the in-hand portrait and the big inspect view. A distinct
large-format version is optional and goes in `card_portraits/big/<slug>.png`; an unfinished tier goes in
`card_portraits/beta/<slug>.png` (see the tiers in [../PROCESS.md](../PROCESS.md)). Until a card has any
of the three it draws the shared per-type placeholder, so partial delivery never looks broken.

The Description column is the card's real rules text, tags stripped — it is what the art has to read
against, and the only reliable guide to what a card is actually about.

| File | Card | Description | Status |
|---|---|---|---|
{chr(10).join(rows)}
"""


def powers_doc():
    t = table("powers")
    rows = []
    for i in ids("powers"):
        if i in POWERS_WITHOUT_ICON:
            continue
        s = slug(i)
        desc = clean(t.get(i + ".description") or t.get(i + ".smartDescription"))
        rows.append(f"| `{s}.png` | {t.get(i + '.title', '')} | {desc} | {status(f'powers/{s}.png')} | {status(f'powers/big/{s}.png')} |")
    excluded = "\n".join(f"- `{slug(i)}` — {t.get(i + '.title', '')}" for i in sorted(POWERS_WITHOUT_ICON))
    return f"""# Power icons

{BANNER}

**{len(rows) * 2} images · two sizes per power**

- `TheUnderstudy/images/powers/big/<slug>.png` — **256x256**, the power-inspect view
- `TheUnderstudy/images/powers/<slug>.png` — **128x128**, the combat status icon

The current 15 shipped icons are 60x60 in both folders and byte-identical to each other, so there is no
real "big" art anywhere yet; all of them are **redraws**, not carry-overs. A power with no icon renders
the base game's red *missing* glyph — deliberately, so unfinished powers are visibly unfinished. This is
the most visible in-combat art defect and the highest-value category to finish first.

Icons are read at a glance, at small size, layered over a creature. Silhouette and one dominant colour
do the work; detail does not survive 128px.

| File | Power | Effect | 128 | 256 |
|---|---|---|---|---|
{chr(10).join(rows)}

## Deliberately without art

These need no icon and are excluded from the count and from the coverage test:

{excluded}
"""


def relics_potions_doc():
    rt, pt = table("relics"), table("potions")
    relic_rows = []
    for i in ids("relics"):
        s = slug(i)
        flavor = clean(rt.get(i + ".flavor"))
        relic_rows.append(
            f"| `{s}.png` | {rt.get(i + '.title', '')} | {clean(rt.get(i + '.description'))} | "
            f"*{flavor}* | {status(f'relics/{s}.png')} / {status(f'relics/outline/{s}.png')} / {status(f'relics/big/{s}.png')} |")
    potion_rows = []
    for i in ids("potions"):
        s = slug(i)
        potion_rows.append(
            f"| `{s}.png` | {pt.get(i + '.title', '')} | {clean(pt.get(i + '.description'))} | "
            f"{status(f'potions/{s}.png')} / {status(f'potions/outline/{s}.png')} |")
    return f"""# Relic and potion icons

{BANNER}

## Relics — {len(relic_rows)} relics x 3 pieces = {len(relic_rows) * 3} images

- `images/relics/<slug>.png` — **128x128** packed icon
- `images/relics/outline/<slug>.png` — **128x128** outline (a solid silhouette; the compendium tints it
  to the character's gold, `#f0c040`)
- `images/relics/big/<slug>.png` — **256x256** inspect view

All three are registered through BaseLib's `RelicImageOverridePatch` in
`TheUnderstudyCode/Patches/RelicOutlineOverride.cs`, which already resolves each piece by slug — dropping
the file in is the whole adoption step. Until a bespoke outline exists the seven reward-pool relics fall
back to a shared generic outline shape; the starter and event relics have no such fallback.

The flavor column is the relic's flavour text. For **False Mask / True Mask** it is worth reading
[../../LORE.md](../../LORE.md) section 7 first — the mask is the character's central image, not just a
prop, and these two are the first relic art any player sees.

| File | Relic | Effect | Flavor | icon / outline / big |
|---|---|---|---|---|
{chr(10).join(relic_rows)}

## Potions — {len(potion_rows)} potions x 2 pieces = {len(potion_rows) * 2} images

- `images/potions/<slug>.png` — **256x256** packed image
- `images/potions/outline/<slug>.png` — **256x256** outline, tinted gold by the Potion Lab

Wired on `UnderstudyPotion` and resolved by slug; null until the file exists, so the game keeps its
default potion sprite in the meantime.

| File | Potion | Effect | image / outline |
|---|---|---|---|
{chr(10).join(potion_rows)}
"""


if __name__ == "__main__":
    OUT.mkdir(parents=True, exist_ok=True)
    write("CARDS.md", cards_doc())
    write("POWERS.md", powers_doc())
    write("RELICS_POTIONS.md", relics_potions_doc())
